### ISSUE TITLE
Cell metadata table

### ISSUE THREAD

**Issue by jfear** [jfear/larval_gonad#129]
### Story
The cell metadata table relates all additional information to each cell id.

**Rows:** Cell ID

**Columns:**
- [ ] flag is cell (called a cell)
- [ ] flag is doublet
- [ ] assigned cell type
- [ ] UMAP coordinates
- [ ] ???
