### ISSUE TITLE
Gene metadata table

### ISSUE THREAD

**Issue by jfear** [jfear/larval_gonad#130]
### Story

The gene metadata table relates all additional information to each FBgn.

**Rows:** FBgn

**Columns:**
- [ ] gene symbol
- [ ] chrom
- [ ] start
- [ ] end
- [ ] strand
- [ ] Literature information (need to think about what columns)
- [ ] Biomarkers columns (need to unstack)
- [ ] Protein trap scores
- [ ] flag commonly expressed
- [ ] Tau score
- [ ] TSPS score
- [ ] flag testis-biased
- [ ] flag ovary-biased
- [ ] flag SP-biased (SP vs EPS)
- [ ] flag EPS-biased (SP vs EPS or EPS vs PS)
- [ ] flag PS-biased (EPS vs PS)
- [ ] flag intronless gene
- [ ] flag retro gene
- [ ] flag ortholog
- [ ] ???
