### ISSUE TITLE
PS-biased X-linked genes

### ISSUE THREAD

**Issue by jfear** [jfear/larval_gonad#186]
### Story
The demasculinization of the X shows a depletion of X-linked male-biased genes. Male-biased gene expression is highly correlated with male-biased expression. We expect a demasculinization of the X in PS-biased genes. I do not know if we should expect the same in SP or EPS-biased genes.

Looking back at the literature I see a reference to mammals that suggests primary spermatocyte genes are actually enriched on the X, but pre-genomics. 

### Questions
- [ ] Do we see a demasculinization of SP-biased genes?
- [ ] Do we see a demasculinization of EPS-biased genes?
- [ ] Do we see a demasculinization of PS-biased genes?

### Tasks
- [ ] Demasculinization bar plots for each gene set.
- [ ] Regress PS-Biased and Testis-biased genes.
    * Split by chromosome
- [ ] GO analysis of PS-biased X-linked genes.
