### ISSUE TITLE
Preliminary: Larval Gonad scRNA-Seq

### ISSUE THREAD

**Issue by jfear** [jfear/larval_gonad#44]
### Story
Sharvani has sequenced two samples of larval gonads (testis, ovary). The goal of this preliminary study is to get a feel for scRNA-Seq data, and determine how many cells are needed to answer the types of questions we want to ask. 

### Questions and Tasks
- [x] What set of scRNA-Seq tools should we use for these analysis and why?
- [x] What is the overall quality of scRNA-Seq data that we get from the 10x genomics system?
- [x] How much data do we need, for scRNA-Seq to be useful?

### Definition of Done
- [x] A scRNA-Seq workflow.
- [x] A plan on how to proceed with future scRNA-Seq experiments.
- [x] Preliminary analysis looking at germline soma communication.
