### ISSUE TITLE
Demasculinization of the X

### ISSUE THREAD

**Issue by jfear** [jfear/larval_gonad#67]
### Story
Demasculinization of the X is an interesting subject to interpret these results. Need to explore the genes that have moved off the X and see if they are expressed and at what stage. If expression is in the spermatigonia stage, then this may suggest  sexual antagonism as a function, while if they are expressed later this would suggest a role of MSCI.

### Questions and Tasks
- [x] Get X->A gene list from Maria
- [x] Get differential expression results among the various clusters
- [x] See if there is an enrichment of X->A genes in given clusters
- [ ] Get orthologous expression from Haiwang
- [ ] Think of other things to look for.

### Definition of done
- [ ] This is more of an epic, don't really have a definition of done.
