### ISSUE TITLE
How to handle missingness

### ISSUE THREAD

**Issue by jfear** [jfear/larval_gonad#73]
### Story
Sparsity is a known issue with scRNA-seq. For DCC, missingness may not be a factor if we focus on "expressed" genes and see how they behave. However, a feature of MSCI is silencing of genes on the X which is conflated with missingness. To explore this issue completely, I need to explore both different gene sets and correctly model silencing vs missingness.

### Questions and Tasks
- [ ] How can we model missingness vs silencing?
- [ ] What gene set(s) to use for looking at DCC and MSCI?
- [ ] How to depict DCC?
- [ ] How to depict MSCI?
- [ ] How to test for DCC?
- [ ] How to test for MSCI?

### Definition of done
- [ ] Defined method for looking at both DCC and MSCI
