### ISSUE TITLE
Bulk RNA-Seq Analysis

### ISSUE THREAD

**Issue by jfear** [jfear/larval_gonad#81]
### Story
Prior to running single cell RNA-seq, Sharvani generated several bulk RNA-seq libraries. These libraries are third instar larval gonads, and include several different dissection/dissociation conditions. She has the following conditions:

Abrv | Description
-----|------------
TF | Pool of testis with small amounts of fat body attached.
OF | Pool of ovary with small amounts of fat body attached.
FT | Pool of fat body cells from around a pool of testis.
FO | Pool of fat body cells from around a pool of ovary.
TCP | Pool of testis cleaned of fat body with papain.
OCP | Pool of ovary cleaned of fat body with papain.
TDP | Pool of testis cleaned dissociated with papain.
TDT | Pool of testis cleaned dissociated with trypsin.

### Questions and Tasks
- [ ] What are the gene expression differences from cleaning.
- [ ] What are the gene expression differences from dissociating.

### Definition of done
- [ ] GEO submitted
- [ ] Written version of methods
- [ ] Finalized analysis summary
