### ISSUE TITLE
Bulk RNA-Seq vs scRNA-Seq

### ISSUE THREAD

**Issue by jfear** [jfear/larval_gonad#84]
### Story
We are interested in seeing how well scRNA-seq can recapitulate the bulk RNA-seq results. 

### Questions and Tasks
- [ ] How correlated are bulk vs sc samples?
- [ ] How many genes are differentially expressed?

### Definition of done
- [ ] Written up methods
- [ ] Summary of these results.
