### ISSUE TITLE
scRNA-Seq Analysis

### ISSUE THREAD

**Issue by jfear** [jfear/larval_gonad#88]
### Story
Analysis of scRNA-seq data. This includes alignment, gene level counts, generation of clusters, and differential expression among clusters.

### Questions and Tasks
- [X] Run cell ranger to generate alignments and coverage counts.
- [X] Decide on dimensionality reduction methods
- [X] Align multiple replicates
- [X] Create clusters
- [X] One vs rest differential expression
- [X] Within germ cell differential expression
- [ ] Sub-cluster germ cells
- [x] trajectory analysis
